version: '3'

services:
  api-query:
    env_file:
      - ./.env
    restart: always
    build: ./backend/api-query
    networks:
      - overlay
    depends_on:
      - "${ES_HOST}"
      - "${RABBIT_HOST}"
    volumes:
      - app-volume:/usr/src/app/storage
      - tmp-volume:/tmp

  api-command:
    build: ./backend/api-command
    restart: always
    env_file:
      - ./.env
    networks:
      - overlay
    depends_on:
      - "${MYSQL_HOST}"
      - "${RABBIT_HOST}"
    volumes:
      - app-volume:/usr/src/app/storage
      - tmp-volume:/tmp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    restart: always
    env_file:
      - ./.env
    networks:
      - overlay
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mysql:
    build: ./db/
    restart: always
    networks:
      - overlay
    env_file:
      - ./.env
    volumes:
      - sqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    env_file:
      - ./.env
    depends_on:
      - "${MYSQL_HOST}"
    ports:
      - 8080:8080
    networks:
      - overlay

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - overlay
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  frontend:
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:80"
    networks:
      - overlay
    command: /bin/bash -c "cp /etc/nginx/conf.d/mysite.template /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - api-query
      - api-command

networks:
  overlay:
volumes:
  app-volume:
  tmp-volume:
  esdata:
  sqldata:
  rabbitmqdata:
