version: '3'

services:
  api-query:
    build: ./backend/api-query
    env_file:
      - ./.env
    ports:
     - "${API_QUERY_PORT}:${API_QUERY_PORT}"
    networks:
      - overlay
    depends_on:
      - "${ES_HOST}"
      - "${RABBIT_HOST}"
  api-command:
    build: ./backend/api-command
    env_file:
      - ./.env
    ports:
      - "${API_COMMAND_PORT}:${API_COMMAND_PORT}"
    networks:
      - overlay
    depends_on:
      - "${MYSQL_HOST}"
      - "${RABBIT_HOST}"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    env_file:
      - ./.env
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - overlay

  mysql:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - overlay
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - overlay

  
  frontend:
    build: .
    env_file:
      - ./.env
    ports:
      - "80:80"
    networks:
      - overlay
    command: /bin/bash -c "mv /etc/nginx/conf.d/mysite.template /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - api-query
      - api-command

networks:
  overlay: