version: '3'

services:
  api-query:
    build: ./backend/api-query
    env_file:
      - ./.env
    ports:
     - "${API_QUERY_PORT}:${API_QUERY_PORT}"
    depends_on:
      - "${ES_HOST}"
      - "${RABBIT_HOST}"
  api-command:
    build: ./backend/api-command
    env_file:
      - ./.env
    ports:
      - "${API_COMMAND_PORT}:${API_COMMAND_PORT}"
    depends_on:
      - "${MYSQL_HOST}"
      - "${RABBIT_HOST}"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    env_file:
      - ./.env
    ports:
      - "9300:9300"
      - "9200:9200"

  mysql:
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  
  frontend:
    build: .
    env_file:
      - ./.env
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/node.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - api-query
      - api-command