version: '3'

services:
  api-query:
    build: ./backend/api-query
    ports:
     - "3000:3000"
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./api:/app/api-query

#   elasticsearch: # Elasticsearch Instance
#     container_name: elasticsearch
#     image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
#     volumes: # Persist ES data in seperate "esdata" volume
#       - esdata:/usr/share/elasticsearch/data
#     environment:
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - discovery.type=single-node
#     ports: # Expose ElasticSearch ports
#       - "9300:9300"
#       - "9200:9200"
# volumes:
#   esdata: