version: '3'

services:
  api-query:
    build: ./backend/api-query
    ports:
     - "3000:3000"
    volumes:
     - ./api:/app/api-query
     - /usr/src/app/node_modules/
  api-command:
    build: ./backend/api-command
    ports:
     - "3001:3001"
    volumes:
     - ./api:/app/api-command
     - /usr/src/app/node_modules/

  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose ElasticSearch ports
      - "9300:9300"
      - "9200:9200"
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always