version: '3'

services:
  api-query:
    build: ./backend/api-query
    env_file:
      - ./.env
    ports:
     - "${API_QUERY_PORT}:${API_QUERY_PORT}"
    depends_on:
      - "${ES_HOST}"
      - "${RABBIT_HOST}"
  api-command:
    build: ./backend/api-command
    env_file:
      - ./.env
    ports:
      - "${API_COMMAND_PORT}:${API_COMMAND_PORT}"
    depends_on:
      - "${MYSQL_HOST}"
      - "${RABBIT_HOST}"


  frontend: # Nginx Server For Frontend App
    env_file:
      - ./.env
    image: nginx
    volumes: # Serve local "public" dir
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80" # Forward site to localhost:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    env_file:
      - ./.env
    ports: # Expose ElasticSearch ports
      - "9300:9300"
      - "9200:9200"

  mysql:
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"