version: '2'
services:
  backend:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_PASSWORD: abc12345678
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: abc12345678